export default {
  Login: 'Login',
  SignUp: 'SignUp',
  Splash: 'Splash',
  Home: 'Home',
  Today: 'Today',
  Profile: 'Profile',
  Shows: 'Shows',
  Expenses: 'Expenses',
  ShowDetails: 'ShowDetails',
  Schedule: 'Schedule',
  Venue: 'Venue',
  TravelAndHotel: 'TravelAndHotel',
  TourDetails: 'TourDetails',
  Contacts: 'Contacts',
  Budget: 'Budget',
  ExpenseDetails: 'ExpenseDetails',
  NearbyMap: 'NearbyMap',
};
